##' .. content for \description{} (no empty lines) ..
##'
##' .. content for \details{} ..
##'
##' @title

##' @return
##' @author whtns
##' @export
tabulate_msk_impact_genes <- function() {

  data.frame(
                                  stringsAsFactors = FALSE,
                                       check.names = FALSE,
                                                SYMBOL = c("ABL1", "AKT1",
                                                         "AKT2","AKT3","ALK",
                                                         "ALOX12B","APC","AR",
                                                         "ARAF","ARID1A",
                                                         "ARID1B","ARID2","ARID5B",
                                                         "ASXL1","ASXL2",
                                                         "ATM","ATR","ATRX",
                                                         "AURKA","AURKB","AXIN1",
                                                         "AXIN2","AXL","B2M",
                                                         "BAP1","BARD1","BBC3",
                                                         "BCL2","BCL2L1",
                                                         "BCL2L11","BCL6","BCOR",
                                                         "BLM","BMPR1A","BRAF",
                                                         "BRCA1","BRCA2",
                                                         "BRD4","BRIP1","BTK",
                                                         "CARD11","CASP8","CBFB",
                                                         "CBL","CCND1",
                                                         "CCND2","CCND3","CCNE1",
                                                         "CD274","CD276",
                                                         "CD79B","CDC73","CDH1",
                                                         "CDK12","CDK4","CDK6",
                                                         "CDK8","CDKN1A",
                                                         "CDKN1B","CDKN2A","CDKN2B",
                                                         "CDKN2C","CHEK1",
                                                         "CHEK2","CIC","CREBBP",
                                                         "CRKL","CRLF2",
                                                         "CSF1R","CTCF","CTLA4",
                                                         "CTNNB1","CUL3","DAXX",
                                                         "DCUN1D1","DDR2",
                                                         "DICER1","DIS3","DNMT1",
                                                         "DNMT3A","DNMT3B",
                                                         "DOT1L","E2F3","EED",
                                                         "EGFL7","EGFR","EIF1AX",
                                                         "EP300","EPCAM",
                                                         "EPHA3","EPHA5","EPHB1",
                                                         "ERBB2","ERBB3",
                                                         "ERBB4","ERCC2","ERCC3",
                                                         "ERCC4","ERCC5","ERG",
                                                         "ESR1","ETV1",
                                                         "ETV6","EZH2","FAM123B",
                                                         "FAM175A","FAM46C",
                                                         "FANCA","FANCC","FAT1",
                                                         "FBXW7","FGF19",
                                                         "FGF3","FGF4","FGFR1",
                                                         "FGFR2","FGFR3","FGFR4",
                                                         "FH","FLCN","FLT1",
                                                         "FLT3","FLT4","FOXA1",
                                                         "FOXL2","FOXP1",
                                                         "FUBP1","GATA1","GATA2",
                                                         "GATA3","GNA11",
                                                         "GNAQ","GNAS","GREM1",
                                                         "GRIN2A","GSK3B",
                                                         "H3F3C","HGF","HIST1H1C",
                                                         "HIST1H2BD","HIST1H3B",
                                                         "HNF1A","HRAS",
                                                         "ICOSLG","IDH1","IDH2",
                                                         "IFNGR1","IGF1","IGF1R",
                                                         "IGF2","IKBKE",
                                                         "IKZF1","IL10","IL7R",
                                                         "INPP4A","INPP4B",
                                                         "INSR","IRF4","IRS1",
                                                         "IRS2","JAK1","JAK2",
                                                         "JAK3","JUN","KDM5A",
                                                         "KDM5C","KDM6A","KDR",
                                                         "KEAP1","KIT","KLF4",
                                                         "KRAS","LATS1",
                                                         "LATS2","LMO1","MAP2K1",
                                                         "MAP2K2","MAP2K4",
                                                         "MAP3K1","MAP3K13",
                                                         "MAPK1","MAX","MCL1",
                                                         "MDC1","MDM2","MDM4",
                                                         "MED12","MEF2B","MEN1",
                                                         "MET","MITF","MLH1",
                                                         "KMT2A (MLL)",
                                                         "KMT2D (MLL2)","KMT2C (MLL3)",
                                                         "MPL","MRE11A","MSH2",
                                                         "MSH6","MTOR",
                                                         "MUTYH","MYC","MYCL1",
                                                         "MYCN","MYD88","MYOD1",
                                                         "NBN","NCOR1","NF1",
                                                         "PHOX2B","PIK3C3",
                                                         "PIK3C2G","NF2","NFE2L2",
                                                         "NKX2-1","NKX3-1",
                                                         "NOTCH1","NOTCH2",
                                                         "NOTCH3","NOTCH4","NPM1",
                                                         "NRAS","NSD1",
                                                         "NTRK1","NTRK2","NTRK3",
                                                         "PAK1","PAK7","PALB2",
                                                         "PARK2","PARP1",
                                                         "PAX5","PBRM1","PDCD1",
                                                         "PDGFRA","PDGFRB",
                                                         "PDPK1","PIK3CA","PIK3CB",
                                                         "PIK3CD","PIK3CG",
                                                         "PIK3R1","PIK3R2",
                                                         "PIK3R3","PIM1","PLK2",
                                                         "PMAIP1","PMS1","PMS2",
                                                         "PNRC1","POLE",
                                                         "PPP2R1A","PRDM1",
                                                         "PRKAR1A","PTCH1","PTEN",
                                                         "PTPN11","PTPRD","PTPRS",
                                                         "PTPRT","RAC1",
                                                         "RAD50","RAD51","RAD51C",
                                                         "RAD51L1","RAD51L3",
                                                         "RAD52","RAD54L",
                                                         "RAF1","RARA","RASA1",
                                                         "RB1","RBM10","RECQL4",
                                                         "REL","RET","RFWD2",
                                                         "RHOA","RICTOR",
                                                         "RIT1","RNF43","ROS1",
                                                         "RPS6KA4","RPS6KB2",
                                                         "RPTOR","RUNX1","RYBP",
                                                         "SDHA","SDHAF2",
                                                         "SDHB","SDHC","SDHD",
                                                         "SETD2","SF3B1","SH2D1A",
                                                         "SHQ1","SMAD2",
                                                         "SMAD3","SMAD4","SMARCA4",
                                                         "SMARCB1","SMARCD1",
                                                         "SMO","SOCS1","SOX17",
                                                         "SOX2","SOX9",
                                                         "SPEN","SPOP","SRC",
                                                         "STAG2","STK11","STK40",
                                                         "SUFU","SUZ12","SYK",
                                                         "TBX3","TERT","TET1",
                                                         "TET2","TGFBR1",
                                                         "TGFBR2","TMEM127",
                                                         "TMPRSS2","TNFAIP3",
                                                         "TNFRSF14","TOP1","TP53",
                                                         "TP63","TRAF7","TSC1",
                                                         "TSC2","TSHR","U2AF1",
                                                         "VHL","VTCN1","WT1",
                                                         "XIAP","XPO1",
                                                         "YAP1","YES1"),
    description = c("c-abl.oncogene.1,.non-receptor.tyrosine.kinase", "v-akt murine thymoma viral oncogene homolog 1",
                                                         "v-akt murine thymoma viral oncogene homolog 2",
                                                         "v-akt murine thymoma viral oncogene homolog 3 (protein kinase B, gamma)",
                                                         "anaplastic lymphoma receptor tyrosine kinase",
                                                         "arachidonate 12-lipoxygenase, 12R type",
                                                         "adenomatous polyposis coli",
                                                         "androgen receptor",
                                                         "v-raf murine sarcoma 3611 viral oncogene homolog",
                                                         "AT rich interactive domain 1A (SWI-like)",
                                                         "AT rich interactive domain 1B (SWI1-like)",
                                                         "AT rich interactive domain 2 (ARID, RFX-like)",
                                                         "AT rich interactive domain 5B (MRF1-like)",
                                                         "additional sex combs like 1 (Drosophila)",
                                                         "additional sex combs like 2 (Drosophila)",
                                                         "ataxia telangiectasia mutated",
                                                         "ataxia telangiectasia and Rad3 related",
                                                         "alpha thalassemia/mental retardation syndrome X-linked",
                                                         "aurora kinase A",
                                                         "aurora kinase B",
                                                         "axin 1","axin 2",
                                                         "AXL receptor tyrosine kinase",
                                                         "beta-2-microglobulin",
                                                         "BRCA1 associated protein-1 (ubiquitin carboxy-terminal hydrolase)",
                                                         "BRCA1 associated RING domain 1",
                                                         "BCL2 binding component 3",
                                                         "B-cell CLL/lymphoma 2",
                                                         "BCL2-like 1",
                                                         "BCL2-like 11 (apoptosis facilitator)",
                                                         "B-cell CLL/lymphoma 6",
                                                         "BCL6 corepressor",
                                                         "Bloom syndrome, RecQ helicase-like",
                                                         "bone morphogenetic protein receptor, type IA",
                                                         "v-raf murine sarcoma viral oncogene homolog B1",
                                                         "breast cancer 1, early onset",
                                                         "breast cancer 2, early onset",
                                                         "bromodomain containing 4",
                                                         "BRCA1 interacting protein C-terminal helicase 1",
                                                         "Bruton agammaglobulinemia tyrosine kinase",
                                                         "caspase recruitment domain family, member 11",
                                                         "caspase 8, apoptosis-related cysteine peptidase",
                                                         "core-binding factor, beta subunit",
                                                         "Cas-Br-M (murine) ecotropic retroviral transforming sequence",
                                                         "cyclin D1","cyclin D2",
                                                         "cyclin D3",
                                                         "cyclin E1","CD274 molecule",
                                                         "CD276 molecule",
                                                         "CD79b molecule, immunoglobulin-associated beta",
                                                         "cell division cycle 73, Paf1/RNA polymerase II complex component, homolog (S. cerevisiae)",
                                                         "cadherin 1, type 1, E-cadherin (epithelial)",
                                                         "cyclin-dependent kinase 12",
                                                         "cyclin-dependent kinase 4",
                                                         "cyclin-dependent kinase 6",
                                                         "cyclin-dependent kinase 8",
                                                         "cyclin-dependent kinase inhibitor 1A (p21, Cip1)",
                                                         "cyclin-dependent kinase inhibitor 1B (p27, Kip1)",
                                                         "cyclin-dependent kinase inhibitor 2A (melanoma, p16, inhibits CDK4)",
                                                         "cyclin-dependent kinase inhibitor 2B (p15, inhibits CDK4)",
                                                         "cyclin-dependent kinase inhibitor 2C (p18, inhibits CDK4)",
                                                         "CHK1 checkpoint homolog (S. pombe)",
                                                         "CHK2 checkpoint homolog (S. pombe)",
                                                         "capicua homolog (Drosophila)",
                                                         "CREB binding protein",
                                                         "v-crk sarcoma virus CT10 oncogene homolog (avian)-like",
                                                         "cytokine receptor-like factor 2",
                                                         "colony stimulating factor 1 receptor",
                                                         "CCCTC-binding factor (zinc finger protein)",
                                                         "cytotoxic T-lymphocyte-associated protein 4",
                                                         "catenin (cadherin-associated protein), beta 1, 88kDa",
                                                         "cullin 3",
                                                         "death-domain associated protein",
                                                         "DCN1, defective in cullin neddylation 1, domain containing 1 (S. cerevisiae)",
                                                         "discoidin domain receptor tyrosine kinase 2",
                                                         "dicer 1, ribonuclease type III",
                                                         "DIS3 mitotic control homolog (S. cerevisiae)",
                                                         "DNA (cytosine-5-)-methyltransferase 1",
                                                         "DNA (cytosine-5-)-methyltransferase 3 alpha",
                                                         "DNA (cytosine-5-)-methyltransferase 3 beta",
                                                         "DOT1-like, histone H3 methyltransferase (S. cerevisiae)",
                                                         "E2F transcription factor 3",
                                                         "embryonic ectoderm development",
                                                         "EGF-like-domain, multiple 7",
                                                         "epidermal growth factor receptor",
                                                         "eukaryotic translation initiation factor 1A, X-linked",
                                                         "E1A binding protein p300",
                                                         "epithelial cell adhesion molecule",
                                                         "EPH receptor A3",
                                                         "EPH receptor A5","EPH receptor B1",
                                                         "v-erb-b2 erythroblastic leukemia viral oncogene homolog 2, neuro/glioblastoma derived oncogene homolog (avian)",
                                                         "v-erb-b2 erythroblastic leukemia viral oncogene homolog 3 (avian)",
                                                         "v-erb-a erythroblastic leukemia viral oncogene homolog 4 (avian)",
                                                         "excision repair cross-complementing rodent repair deficiency, complementation group 2",
                                                         "excision repair cross-complementing rodent repair deficiency, complementation group 3 (xeroderma pigmentosum group B complementing)",
                                                         "excision repair cross-complementing rodent repair deficiency, complementation group 4",
                                                         "excision repair cross-complementing rodent repair deficiency, complementation group 5",
                                                         "v-ets erythroblastosis virus E26 oncogene homolog (avian)",
                                                         "estrogen receptor 1",
                                                         "ets variant 1",
                                                         "ets variant 6",
                                                         "enhancer of zeste homolog 2 (Drosophila)",
                                                         "family with sequence similarity 123B",
                                                         "family with sequence similarity 175, member A",
                                                         "family with sequence similarity 46, member C",
                                                         "Fanconi anemia, complementation group A",
                                                         "Fanconi anemia, complementation group C",
                                                         "FAT tumor suppressor homolog 1 (Drosophila)",
                                                         "F-box and WD repeat domain containing 7",
                                                         "fibroblast growth factor 19",
                                                         "fibroblast growth factor 3",
                                                         "fibroblast growth factor 4",
                                                         "fibroblast growth factor receptor 1",
                                                         "fibroblast growth factor receptor 2",
                                                         "fibroblast growth factor receptor 3",
                                                         "fibroblast growth factor receptor 4",
                                                         "fumarate hydratase",
                                                         "folliculin",
                                                         "fms-related tyrosine kinase 1 (vascular endothelial growth factor/vascular permeability factor receptor)",
                                                         "fms-related tyrosine kinase 3",
                                                         "fms-related tyrosine kinase 4",
                                                         "forkhead box A1",
                                                         "forkhead box L2",
                                                         "forkhead box P1",
                                                         "far upstream element (FUSE) binding protein 1",
                                                         "GATA binding protein 1 (globin transcription factor 1)",
                                                         "GATA binding protein 2",
                                                         "GATA binding protein 3",
                                                         "guanine nucleotide binding protein (G protein), alpha 11 (Gq class)",
                                                         "guanine nucleotide binding protein (G protein), q polypeptide",
                                                         "GNAS complex locus","gremlin 1",
                                                         "glutamate receptor, ionotropic, N-methyl D-aspartate 2A",
                                                         "glycogen synthase kinase 3 beta",
                                                         "H3 histone, family 3C",
                                                         "hepatocyte growth factor (hepapoietin A; scatter factor)",
                                                         "histone cluster 1, H1c",
                                                         "histone cluster 1, H2bd",
                                                         "histone cluster 1, H3b",
                                                         "HNF1 homeobox A",
                                                         "v-Ha-ras Harvey rat sarcoma viral oncogene homolog",
                                                         "inducible T-cell co-stimulator ligand",
                                                         "isocitrate dehydrogenase 1 (NADP+), soluble",
                                                         "isocitrate dehydrogenase 2 (NADP+), mitochondrial",
                                                         "interferon gamma receptor 1",
                                                         "insulin-like growth factor 1 (somatomedin C)",
                                                         "insulin-like growth factor 1 receptor",
                                                         "insulin-like growth factor 2 (somatomedin A)",
                                                         "inhibitor of kappa light polypeptide gene enhancer in B-cells, kinase epsilon",
                                                         "IKAROS family zinc finger 1 (Ikaros)",
                                                         "interleukin 10",
                                                         "interleukin 7 receptor",
                                                         "inositol polyphosphate-4-phosphatase, type I, 107kDa",
                                                         "inositol polyphosphate-4-phosphatase, type II, 105kDa",
                                                         "insulin receptor",
                                                         "interferon regulatory factor 4",
                                                         "insulin receptor substrate 1",
                                                         "insulin receptor substrate 2",
                                                         "Janus kinase 1",
                                                         "Janus kinase 2",
                                                         "Janus kinase 3",
                                                         "jun proto-oncogene",
                                                         "lysine (K)-specific demethylase 5A",
                                                         "lysine (K)-specific demethylase 5C",
                                                         "lysine (K)-specific demethylase 6A",
                                                         "kinase insert domain receptor (a type III receptor tyrosine kinase)",
                                                         "kelch-like ECH-associated protein 1",
                                                         "v-kit Hardy-Zuckerman 4 feline sarcoma viral oncogene homolog",
                                                         "Kruppel-like factor 4 (gut)",
                                                         "v-Ki-ras2 Kirsten rat sarcoma viral oncogene homolog",
                                                         "LATS, large tumor suppressor, homolog 1 (Drosophila)",
                                                         "LATS, large tumor suppressor, homolog 2 (Drosophila)",
                                                         "LIM domain only 1 (rhombotin 1)",
                                                         "mitogen-activated protein kinase kinase 1",
                                                         "mitogen-activated protein kinase kinase 2",
                                                         "mitogen-activated protein kinase kinase 4",
                                                         "mitogen-activated protein kinase kinase kinase 1",
                                                         "mitogen-activated protein kinase kinase kinase 13",
                                                         "mitogen-activated protein kinase 1",
                                                         "MYC associated factor X",
                                                         "myeloid cell leukemia sequence 1 (BCL2-related)",
                                                         "mediator of DNA-damage checkpoint 1",
                                                         "Mdm2 p53 binding protein homolog (mouse)",
                                                         "Mdm4 p53 binding protein homolog (mouse)",
                                                         "mediator complex subunit 12",
                                                         "myocyte enhancer factor 2B",
                                                         "multiple endocrine neoplasia I",
                                                         "met proto-oncogene (hepatocyte growth factor receptor)",
                                                         "microphthalmia-associated transcription factor",
                                                         "mutL homolog 1, colon cancer, nonpolyposis type 2 (E. coli)",
                                                         "myeloid/lymphoid or mixed-lineage leukemia (trithorax homolog, Drosophila)",
                                                         "myeloid/lymphoid or mixed-lineage leukemia 2",
                                                         "myeloid/lymphoid or mixed-lineage leukemia 3",
                                                         "myeloproliferative leukemia virus oncogene",
                                                         "MRE11 meiotic recombination 11 homolog A (S. cerevisiae)",
                                                         "mutS homolog 2, colon cancer, nonpolyposis type 1 (E. coli)",
                                                         "mutS homolog 6 (E. coli)",
                                                         "mechanistic target of rapamycin (serine/threonine kinase)",
                                                         "mutY homolog (E. coli)",
                                                         "v-myc myelocytomatosis viral oncogene homolog (avian)",
                                                         "v-myc myelocytomatosis viral oncogene homolog 1, lung carcinoma derived (avian)",
                                                         "v-myc myelocytomatosis viral related oncogene, neuroblastoma derived (avian)",
                                                         "myeloid differentiation primary response gene (88)",
                                                         "myogenic differentiation 1","nibrin",
                                                         "nuclear receptor corepressor 1",
                                                         "neurofibromin 1",
                                                         "paired-like homeobox 2b",
                                                         "phosphoinositide-3-kinase, class 3",
                                                         "phosphoinositide-3-kinase, class 2, gamma polypeptide",
                                                         "neurofibromin 2 (merlin)",
                                                         "nuclear factor (erythroid-derived 2)-like 2",
                                                         "NK2 homeobox 1",
                                                         "NK3 homeobox 1","notch 1",
                                                         "notch 2","notch 3",
                                                         "notch 4",
                                                         "nucleophosmin (nucleolar phosphoprotein B23, numatrin)",
                                                         "neuroblastoma RAS viral (v-ras) oncogene homolog",
                                                         "nuclear receptor binding SET domain protein 1",
                                                         "neurotrophic tyrosine kinase, receptor, type 1",
                                                         "neurotrophic tyrosine kinase, receptor, type 2",
                                                         "neurotrophic tyrosine kinase, receptor, type 3",
                                                         "p21 protein (Cdc42/Rac)-activated kinase 1",
                                                         "p21 protein (Cdc42/Rac)-activated kinase 7",
                                                         "partner and localizer of BRCA2",
                                                         "parkinson protein 2, E3 ubiquitin protein ligase (parkin)",
                                                         "poly (ADP-ribose) polymerase 1","paired box 5",
                                                         "polybromo 1",
                                                         "programmed cell death 1",
                                                         "platelet-derived growth factor receptor, alpha polypeptide",
                                                         "platelet-derived growth factor receptor, beta polypeptide",
                                                         "3-phosphoinositide dependent protein kinase-1",
                                                         "phosphoinositide-3-kinase, catalytic, alpha polypeptide",
                                                         "phosphoinositide-3-kinase, catalytic, beta polypeptide",
                                                         "phosphoinositide-3-kinase, catalytic, delta polypeptide",
                                                         "phosphoinositide-3-kinase, catalytic, gamma polypeptide",
                                                         "phosphoinositide-3-kinase, regulatory subunit 1 (alpha)",
                                                         "phosphoinositide-3-kinase, regulatory subunit 2 (beta)",
                                                         "phosphoinositide-3-kinase, regulatory subunit 3 (gamma)","pim-1 oncogene",
                                                         "polo-like kinase 2",
                                                         "phorbol-12-myristate-13-acetate-induced protein 1",
                                                         "PMS1 postmeiotic segregation increased 1 (S. cerevisiae)",
                                                         "PMS2 postmeiotic segregation increased 2 (S. cerevisiae)",
                                                         "proline-rich nuclear receptor coactivator 1",
                                                         "polymerase (DNA directed), epsilon",
                                                         "protein phosphatase 2, regulatory subunit A, alpha",
                                                         "PR domain containing 1, with ZNF domain",
                                                         "protein kinase, cAMP-dependent, regulatory, type I, alpha (tissue specific extinguisher 1)","patched 1",
                                                         "phosphatase and tensin homolog",
                                                         "protein tyrosine phosphatase, non-receptor type 11",
                                                         "protein tyrosine phosphatase, receptor type, D",
                                                         "protein tyrosine phosphatase, receptor type, S",
                                                         "protein tyrosine phosphatase, receptor type, T",
                                                         "ras-related C3 botulinum toxin substrate 1 (rho family, small GTP binding protein Rac1)",
                                                         "RAD50 homolog (S. cerevisiae)",
                                                         "RAD51 homolog (RecA homolog, E. coli) (S. cerevisiae)",
                                                         "RAD51 homolog C (S. cerevisiae)",
                                                         "RAD51-like 1 (S. cerevisiae)",
                                                         "RAD51-like 3 (S. cerevisiae)",
                                                         "RAD52 homolog (S. cerevisiae)",
                                                         "RAD54-like (S. cerevisiae)",
                                                         "v-raf-1 murine leukemia viral oncogene homolog 1",
                                                         "retinoic acid receptor, alpha",
                                                         "RAS p21 protein activator (GTPase activating protein) 1",
                                                         "retinoblastoma 1",
                                                         "RNA binding motif protein 10",
                                                         "RecQ protein-like 4",
                                                         "v-rel reticuloendotheliosis viral oncogene homolog (avian)",
                                                         "ret proto-oncogene",
                                                         "ring finger and WD repeat domain 2",
                                                         "ras homolog gene family, member A",
                                                         "RPTOR independent companion of MTOR, complex 2",
                                                         "Ras-like without CAAX 1",
                                                         "ring finger protein 43",
                                                         "c-ros oncogene 1 , receptor tyrosine kinase",
                                                         "ribosomal protein S6 kinase, 90kDa, polypeptide 4",
                                                         "ribosomal protein S6 kinase, 70kDa, polypeptide 2",
                                                         "regulatory associated protein of MTOR, complex 1",
                                                         "runt-related transcription factor 1",
                                                         "RING1 and YY1 binding protein",
                                                         "succinate dehydrogenase complex, subunit A, flavoprotein (Fp)",
                                                         "succinate dehydrogenase complex assembly factor 2",
                                                         "succinate dehydrogenase complex, subunit B, iron sulfur (Ip)",
                                                         "succinate dehydrogenase complex, subunit C, integral membrane protein, 15kDa",
                                                         "succinate dehydrogenase complex, subunit D, integral membrane protein",
                                                         "SET domain containing 2",
                                                         "splicing factor 3b, subunit 1, 155kDa",
                                                         "SH2 domain containing 1A",
                                                         "SHQ1 homolog (S. cerevisiae)",
                                                         "SMAD family member 2",
                                                         "SMAD family member 3",
                                                         "SMAD family member 4",
                                                         "SWI/SNF related, matrix associated, actin dependent regulator of chromatin, subfamily a, member 4",
                                                         "SWI/SNF related, matrix associated, actin dependent regulator of chromatin, subfamily b, member 1",
                                                         "SWI/SNF related, matrix associated, actin dependent regulator of chromatin, subfamily d, member 1",
                                                         "smoothened homolog (Drosophila)",
                                                         "suppressor of cytokine signaling 1",
                                                         "SRY (sex determining region Y)-box 17",
                                                         "SRY (sex determining region Y)-box 2",
                                                         "SRY (sex determining region Y)-box 9",
                                                         "spen homolog, transcriptional regulator (Drosophila)",
                                                         "speckle-type POZ protein",
                                                         "v-src sarcoma (Schmidt-Ruppin A-2) viral oncogene homolog (avian)",
                                                         "stromal antigen 2",
                                                         "serine/threonine kinase 11",
                                                         "serine/threonine kinase 40",
                                                         "suppressor of fused homolog (Drosophila)",
                                                         "suppressor of zeste 12 homolog (Drosophila)",
                                                         "spleen tyrosine kinase","T-box 3",
                                                         "telomerase reverse transcriptase",
                                                         "tet oncogene 1",
                                                         "tet oncogene family member 2",
                                                         "transforming growth factor, beta receptor 1",
                                                         "transforming growth factor, beta receptor II (70/80kDa)",
                                                         "transmembrane protein 127",
                                                         "transmembrane protease, serine 2",
                                                         "tumor necrosis factor, alpha-induced protein 3",
                                                         "tumor necrosis factor receptor superfamily, member 14 (herpesvirus entry mediator)",
                                                         "topoisomerase (DNA) I",
                                                         "tumor protein p53",
                                                         "tumor protein p63",
                                                         "TNF receptor-associated factor 7",
                                                         "tuberous sclerosis 1",
                                                         "tuberous sclerosis 2",
                                                         "thyroid stimulating hormone receptor",
                                                         "U2 small nuclear RNA auxiliary factor 1",
                                                         "von Hippel-Lindau tumor suppressor",
                                                         "V-set domain containing T cell activation inhibitor 1","Wilms tumor 1",
                                                         "X-linked inhibitor of apoptosis",
                                                         "exportin 1 (CRM1 homolog, yeast)",
                                                         "Yes-associated protein 1",
                                                         "v-yes-1 Yamaguchi sarcoma viral oncogene homolog 1")
  ) %>% 
        dplyr::pull(SYMBOL)

}
